In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

my_data = pd.read_csv("data/drug200.csv", delimiter=",")

# Xem thông tin và kích thước của dữ liệu
print(my_data.shape)
print("--------------Dữ liệu ban đầu-----------------")
print(my_data[0:5]) #lấy 5 dòng đầu

# Chuẩn bị dữ liệu đầu vào (X) và đầu ra (y) || Dưới quá quá trình chuyển đổi dữ liệu thành số
X = my_data[['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K']].values

le_sex = preprocessing.LabelEncoder()
le_sex.fit(['F','M'])
X[:,1] = le_sex.transform(X[:,1]) 

le_BP = preprocessing.LabelEncoder() #Blood Pressure huyết áp
le_BP.fit([ 'LOW', 'NORMAL', 'HIGH'])
X[:,2] = le_BP.transform(X[:,2])

le_Chol = preprocessing.LabelEncoder()
le_Chol.fit([ 'NORMAL', 'HIGH'])
X[:,3] = le_Chol.transform(X[:,3])

print("--------------Dữ liệu đầu vào sau khi được số hoá-----------------")
print(X[0:5])



mean = X[:, -1].mean() #Tính giá trị trung bình của cột'Na_to_K'
std = X[:, -1].std() #Tính độ lệch chuẩn cột 'Na_to_K'
X[:, -1] = (X[:, -1] - mean) / std #Chuẩn hóa cột này bằng cách trừ đi giá trị trung bình và chia cho độ lệch chuẩn.
print("--------------X sau khi cột Na_to_K được chuẩn hoá-----------------")
print(X[0:5])

print("--------------Cột drug ban đầu-----------------")
y = my_data["Drug"]
print(y[0:5])

le_drug = preprocessing.LabelEncoder()
le_drug.fit(['drugA','drugB', 'drugC', 'drugX', 'drugY'])
y = le_drug.transform(y)
print("--------------Cột drug sau khi chuẩn hoá-----------------")
print(y[0:5])


(200, 6)
--------------Dữ liệu ban đầu-----------------
   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY
--------------Dữ liệu đầu vào sau khi được số hoá-----------------
[[23 0 0 0 25.355]
 [47 1 1 0 13.093]
 [47 1 1 0 10.114]
 [28 0 2 0 7.798]
 [61 0 1 0 18.043]]
--------------X sau khi cột Na_to_K được chuẩn hoá-----------------
[[23 0 0 0 1.2865221173753503]
 [47 1 1 0 -0.4151453955143358]
 [47 1 1 0 -0.8285581765368749]
 [28 0 2 0 -1.1499626749753444]]
--------------Cột drug ban đầu-----------------
0    drugY
1    drugC
2    drugC
3    drugX
4    drugY
Name: Drug, dtype: object
--------------Cột drug sau khi chuẩn hoá-----------------
[4 2 2 3 4]
