<!-- <a href="https://www.bigdatauniversity.com"><img src="https://ibm.box.com/shared/static/cw2c7r3o20w9zn8gkecaeyjhgw3xdgbj.png" width="400" align="center"></a>
 -->
 
<!-- # Released under  -->

Copyright (c) 2013 Mark Otto. Copyright (c) 2017 Andrew Fong. MIT License

====== Nguồn http://users.soict.hust.edu.vn/khoattq/ml-dm-course/ ======




<h1><center>Xây dựng mô hình Random Forest cho bài toán phân loại</center></h1>

 - Trong bài thực hành này, chúng ta sử dụng mô hình Random Forest để phân loại bệnh nhân vào các loại thuốc khác nhau. Mô hình sau khi huấn luyện được sử dụng để dự đoán nhãn cho bệnh nhân mới từ đó có thể tìm được thuốc thích hợp
<!-- In this lab exercise, you will learn a popular machine learning algorithm, Decision Tree. You will use this classification algorithm to build a model from historical data of patients, and their response to different medications. Then you use the trained decision tree to predict the class of a unknown patient, or to find a proper drug for a new patient. -->

<h1>Nội dung thực hành</h1>

<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ol>
        <li><a href="#about_dataset">Giới thiệu về dữ liệu</a></li>
        <li><a href="#downloading_data">Tải dữ liệu</a></li>
        <li><a href="#pre-processing">Tiền xử lý dữ liệu</a></li>
        <li><a href="#setting_up_tree">Cài đặt mô hình Random Forest</a></li>
        <li><a href="#modeling">Huấn luyện</a></li>
        <li><a href="#prediction">Dự đoán</a></li>
        <li><a href="#evaluation">Đánh giá mô hình</a></li>
        <li><a href="#evaluation">Đánh giá ảnh hưởng của các thuộc tính với nhãn</a></li>
    </ol>
</div>
<br>
<hr>

Import các thư viện sau:
<ul>
    <li> <b>numpy (as np)</b> </li>
    <li> <b>pandas</b> </li>
    <li> <b>RandomForestClassifier</b> from <b>sklearn.ensemble</b> </li>
</ul>

In [2]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

<div id="Giới thiệu về dữ liệu">
    <h2>Giới thiệu về dữ liệu</h2>
    Giả sử bạn là một người nghiên cứu về dữ liệu y học, bạn đã thu thập được một tập dữ liệu các bệnh nhân của cùng một loại bệnh, trong khi điều trị mỗi bệnh nhân phản ứng với 1 trong 5 loại thuốc A, B, c, x và y.
    <br>
    <br>
    Công việc cần làm là xây dựng một mô hình nhằm tìm ra loại thuốc phù hợp cho bênh nhân mới bị mắc loại bênh trên. Các trường dữ liệu gồm gồm có: Age, Sex, Blood Pressur, Cholesterol, Na_to_K, Drug
    <br>
    <br>
    Chúng ta sử dụng phần dữ liệu huấn luyện để xây dựng mô hình Random Forest và đánh giá mô hình này trên tập đánh giá, sau đó sử dụng mô hình để suy diễn trên bệnh nhân mới
</div>


<div id="downloading_data"> 
    <h2>Load dữ liệu từ file</h2>
<!--     Sử dụng wget để tải dữ liệu từ IBM Object Storage. -->
</div>

Đọc dữ liệu vào pandas dataframe

In [3]:
my_data = pd.read_csv("data/drug200.csv", delimiter=",")
my_data[0:5]

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

Kích thước của dữ liệu

In [4]:
my_data.shape

(200, 6)

<div href="pre-processing">
    <h2>Tiền xử lý dữ liệu</h2>
</div>

<b>my_data</b> là  Drug.csv sau khi đọc vào pandas dataframe, chúng ta định nghĩa các tham số sau: <br>

<ul>
    <li> <b> X </b> as the <b> Ma trận thuộc tính </b> (data of my_data) 
    <li> <b> y </b> as the <b> Vector thuốc phản hồi (target) </b> </li>
</ul>

In [6]:
X = my_data[['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K']].values
X[0:5]

array([[23, 'F', 'HIGH', 'HIGH', 25.355],
       [47, 'M', 'LOW', 'HIGH', 13.093],
       [47, 'M', 'LOW', 'HIGH', 10.114],
       [28, 'F', 'NORMAL', 'HIGH', 7.798],
       [61, 'F', 'LOW', 'HIGH', 18.043]], dtype=object)

Một vài trường trong dữ liệu có dạng categorical như __Sex__ hoặc __BP__. Mô hình Random Forest trong thư viện chỉ xử lý với dữ liệu số thực do đó chúng ta cần chuyển các thuộc tính trên về dạng số thực tương ứng. Sử dụng  __skearn.preprocessing__ để chuyển dữ liệu dạng categorical về số thực

In [7]:
from sklearn import preprocessing
le_sex = preprocessing.LabelEncoder()
le_sex.fit(['F','M'])
X[:,1] = le_sex.transform(X[:,1]) 


le_BP = preprocessing.LabelEncoder()
le_BP.fit([ 'LOW', 'NORMAL', 'HIGH'])
X[:,2] = le_BP.transform(X[:,2])


le_Chol = preprocessing.LabelEncoder()
le_Chol.fit([ 'NORMAL', 'HIGH'])
X[:,3] = le_Chol.transform(X[:,3]) 

X[0:5]

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.114],
       [28, 0, 2, 0, 7.798],
       [61, 0, 1, 0, 18.043]], dtype=object)

Dữ liệu target về loại thuốc phản ứng

In [10]:
y = my_data["Drug"]
y[0:5]

0    drugY
1    drugC
2    drugC
3    drugX
4    drugY
Name: Drug, dtype: object

<hr>

<div id="setting_up_tree">
    <h2>Cài đặt mô hình Random Forest</h2>
    Chúng ta chia dữ liệu thành hai phần <b>train</b> và <b>test</b> để huấn luyện và đánh giá mô hình <b>Random Forest</b>. Import <b>train_test_split</b> từ <b>sklearn.cross_validation</b>.
</div>

In [8]:
from sklearn.model_selection import train_test_split

Hàm <b> train_test_split </b> trả về 4 giá trị khác nhau. Chúng ta đặt tên như sau:<br>
X_trainset, X_testset, y_trainset, y_testset <br> <br>
Hàm <b> train_test_split </b> cần các tham số đầu vào: <br>
X, y, test_size=0.3, and random_state=3. <br> <br>
<b>X</b> and <b>y</b> là các ma trận và vector cần chia, <b>test_size</b> là tỉ lệ tập test,và <b>random_state</b> để loại bỏ tính ngẫu nhiên.

In [11]:
X_trainset, X_testset, y_trainset, y_testset = train_test_split(X, y, test_size=0.3, random_state=3)

<h3>Thực hành</h3>
Print kích thước X_trainset and y_trainset. Đảm bảo số chiều tương ứng với nhau

In [12]:
# your code
print(X_trainset)


[[26 0 0 1 19.161]
 [41 0 2 1 22.905]
 [28 0 2 0 19.675]
 [19 0 0 0 13.313]
 [50 1 2 1 15.79]
 [24 1 2 0 25.786]
 [72 1 1 0 16.31]
 [74 0 1 0 20.942]
 [37 0 1 1 12.006]
 [31 1 0 1 17.069]
 [22 0 2 0 8.607]
 [20 0 2 1 9.281]
 [28 0 1 0 13.127]
 [59 0 2 0 13.884]
 [15 1 0 1 17.206]
 [51 0 1 1 23.003]
 [45 1 1 1 10.017]
 [33 0 1 0 33.486]
 [39 1 0 0 9.664]
 [29 0 0 0 29.45]
 [60 1 2 0 15.171]
 [24 0 0 1 18.457]
 [49 0 2 1 9.381]
 [37 1 1 1 8.968]
 [32 0 0 1 10.292]
 [21 0 0 1 28.632]
 [23 1 2 0 12.26]
 [40 1 0 0 27.826]
 [38 1 1 0 18.295]
 [47 1 1 1 30.568]
 [22 0 0 1 22.818]
 [47 1 0 0 10.403]
 [30 0 2 0 10.443]
 [69 1 1 0 15.478]
 [42 0 0 0 21.036]
 [45 1 1 1 8.37]
 [49 1 0 1 6.269]
 [72 1 1 0 6.769]
 [74 1 1 1 11.939]
 [66 0 2 1 8.107]
 [46 1 2 1 7.285]
 [68 0 2 1 27.05]
 [58 0 0 0 19.416]
 [19 0 0 1 25.969]
 [20 1 0 1 35.639]
 [69 1 1 1 11.455]
 [32 0 0 1 25.974]
 [72 1 0 1 9.677]
 [50 0 2 1 12.295]
 [54 1 2 0 24.658]
 [36 0 0 0 11.198]
 [64 0 1 1 25.741]
 [35 1 1 1 9.17]
 [47 0 1 0 1

Print kích thước X_testset and y_testset. Đảm bảo số chiều tương ứng với nhau

In [ ]:
# your code



<hr>

<div id="modeling">
    <h2>Huấn luyện</h2>
    Trước tiên chúng ta cần tạo một đối tượng <b>RandomForestClassifier</b> tên <b>drugTree</b>.<br>
    Khi khởi tạo cần chỉ rõ số cây tương ứng
</div>

In [ ]:
drugTree = RandomForestClassifier(n_estimators=100)
drugTree

Huấn luyện mô hình trên tập <b> X_trainset </b> và vector nhãn tương ứng <b> y_trainset </b>

In [ ]:
drugTree.fit(X_trainset,y_trainset)

<hr>

<div id="prediction">
    <h2>Dự đoán</h2>
    Thực hiện các <b>dự đoán</b> trên tập dữ liệu test và lưu kết quả vào biến <b>predTree</b>.
</div>

In [ ]:
predTree = drugTree.predict(X_testset)

So sánh kết quả dữ đoán <b>predTree</b> và nhãn thật tương ứng <b>y_testset</b>

In [ ]:
print('Nhãn phán đoán')
print (predTree [0:5])
print('Nhãn đúng')
print(list(y_testset)[0:5])

<hr>

<div id="evaluation">
    <h2>Đánh giá thử mô hình</h2>
    Import <b>metrics</b> từ sklearn and kiểm tra độ chính xác của mô hình trên tập test
</div>

In [ ]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_testset, predTree))

<hr>

<div id="evaluation">
    <h2>Đánh giá ảnh hưởng của các thuộc tính với nhãn</h2>
        Đánh giá độ ảnh hưởng của thuộc tính với nhãn là một kỹ thuật để gán điểm số cho các thuộc tính đầu vào của mô hình nhằm cho biết tầm quan trọng của thuộc tính đó khi đưa ra dự đoán.
    <br>
    <br>
    Các điểm số có thể được sử dụng để:
    <ul>
    <li> Hiểu về dữ liệu
    <li> Hiểu về dữ liệu
    <li> Giảm số chiều của dữ liệu bằng việc loại đi các thuộc tính không quan trọng </li>
</ul>
</div>


In [ ]:
print(list(my_data.columns)[0:-1])
print(list(drugTree.feature_importances_))